# Arquitetura geral:
# - Pasta backend/ roda FastAPI com WebSocket (porta 8000)
# - Pasta client/ roda pygame com acesso ao backend via localhost
# - Devcontainer com Docker Compose para isolar ambiente Python

# docker-compose.yml
version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    working_dir: /workspace/backend
    volumes:
      - .:/workspace
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
    ports:
      - "8000:8000"
    networks:
      - pacnet

  # Cliente pygame será testado via terminal do devcontainer

networks:
  pacnet:
    driver: bridge
